version: '3.8'

#services:
#    angular-app:
#        image: nginx:latest
#        container_name: prime-sakai-ng
#        ports:
#            - "90:80"
#        volumes:
#            - ./dist/sakai-ng:/usr/share/nginx/html
#            - ./nginx.conf:/etc/nginx/conf.d/default.conf
#        restart: always

services:
    prime-frontend-service:
        container_name: prime-sakai-fe
        build:
            context: .
            dockerfile: docker-prime-sakai-fe
        ports:
            - "91:80"
